config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'
  #get 'projects/new'
  #get 'projects/index'
  #get 'projects/create'
  #get 'projects/edit'
  #get 'projects/update'
  #get 'projects/destroy'
  resources :projects
  #get 'tasks/index'
  #get 'tasks/new'
  #get 'tasks/create'
  #get 'tasks/edit'
  #get 'tasks/update'
  #get 'tasks/complete'
  #get 'tasks/destroy'
  resources :tasks do
    put :complete, on: :member
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, -> { order "status, priority DESC, created_at" }, dependent: :destroy

  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :title, presence: true

  PRIORITIES = [
      ['Later', 1],
      ['Next', 2],
      ['Now', 3],
  ]

  def complete!
    self.status = true
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  http_basic_authenticate_with name: 'admin', password: 'admin'
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all.order('created_at DESC')
    @project = Project.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    respond_to do |format|
      if @project.save
        format.js
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    @project = Project.find params[:id]
    @project.update_attributes project_params
    respond_to do |format|
      if @project.update_attributes project_params
        format.js
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render json: @project, status: :ok, location: @project }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find params[:id]
    @project.destroy
    redirect_to root_path
  end

  private
  def project_params
    params.require(:project).permit([:name])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.where(status: false).order('priority DESC, created_at')
    @completed_tasks = Task.where(status: true).order('updated_at')
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new task_params
    respond_to do |format|
      if @task.save
        format.js
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
    redirect_to root_path
  end

  def edit
    @task = Task.find params[:id]
  end

  def update
    @task = Task.find params[:id]
    @task.update_attributes task_params
    respond_to do |format|
      if @task.update_attributes task_params
        format.js
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render json: @task, status: :ok, location: @task }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
    redirect_to root_path
  end

  def complete
    @task = Task.find params[:id]
    @task.complete!
    redirect_to root_path
  end

  def destroy
    @task = Task.find params[:id]
    @task.destroy
    redirect_to root_path
  end

  private
  def task_params
    params.require(:task).permit([
                                     :title, :priority, :deadline, :status, :project_id
                                 ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mytestapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <div class="row"><%= yield %></div>    
      <div class="row">
          <div class="copyright text-center">
            <p>&#169; Ruby Garage</p>
          </div>
      </div>
  </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for @project, remote: true, validate: true do |f| %>
	<div class='new-task-input-group'>
			<%= f.input :name, label: false %>
		<div class="input-btn">
			<%= f.button :submit, label: false, class: 'btn btn-primary' %>
		</div>
	</div>
<% end %>

app/views/projects/_project.html.erb
<li>
  <div id="project-<%= project.id %>">
    <div class="project-header">
      <div class="project-header-title">
        <span><i class="fa fa-calendar" aria-hidden="true"></i></span>
        <span class="project-header-name"><%= project.name %></span>
        <div class="project-header-options">
          <span><%= link_to content_tag('span', '', class: 'fa fa-pencil'), edit_project_path(project), remote: true, class: 'action' %></span>
          <span><%= link_to content_tag('span', '', class: 'fa fa-trash'), project, method: :delete, remote: true, class: 'action' %></span>
        </div>
      </div>
    </div>
    <div class='project-body'>
      <div class='new-task-container'>
        <%= simple_form_for Task.new, remote: true, validate: true do |f| %>
          <div class='new-task-input-group'>
              <%= f.input :title, label: false %>
              <%= f.input :priority, label: false, :as => :hidden, :input_html => { :value => 1 } %>
              <%= f.input :status, label: false, :as => :hidden, :input_html => { :value => false } %>
              <%= f.input :project_id, label: false, :as => :hidden, :input_html => { :value => project.id } %>
              <%= f.input :deadline, html5: true, label: false, :as => :hidden%>
            <div class="input-btn">
              <%= f.button :submit, label: false, class: 'btn btn-primary' %>
            </div>
          </div>          
        <% end %>
      </div>
      <div class="buffer">
        <ul id="tasks" class="tasks-list">
          <%= render partial: 'tasks/task', collection: project.tasks  %>
        </ul>
      </div>
    </div>
  </div>
</li>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/create.js.erb
$('#new-project form').remove();
$('#new-project a').show();
$('ul#projects').prepend("<%= j render @project %>")

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/delete.html.erb</p>

app/views/projects/edit.html.erb
<div class="col-md-12">
  <h1>Edit Project</h1>
</div>
<%= render 'form' %>

app/views/projects/edit.js.erb
$('#project-<%= @project.id %>').hide().parent().prepend("<%= j render 'form', project: @project %>");

$(document).mouseup(function(e)
{
    let container = $('#edit_project_<%= @project.id %>');
    if (!container.is(e.target) && container.has(e.target).length === 0)
    {
        container.remove();
        $('#project-<%= @project.id %>').show();
    }

});

app/views/projects/index.html.erb
<h1>SIMPLE TODO LIST
  <br>
  <small>FROM RUBY GARAGE</small>
</h1>
<div class="col-sm-8 col-sm-offset-2">
  <div class="buffer-top">
    <ul id="projects" class="projects-list">
      <%= render @projects %>
    </ul>
  </div>
  <hr />
  <div id="new-project" class="new-project-button">
    <%= link_to "Add TODO list", new_project_path, remote: true, class: 'btn btn-primary' %>
  </div>
  <hr />
</div>

app/views/projects/new.html.erb
<div class="col-md-12">
  <h1>New Project</h1>
</div>
<%= render 'form' %>

app/views/projects/new.js.erb
$('#new-project a').hide().parent().append("<%= j render 'form' %>");

$(document).mouseup(function(e)
{
    let container = $("#new-project form");
    if (!container.is(e.target) && container.has(e.target).length === 0)
    {
        container.remove();
        $('#new-project a').show();
    }

});

$(new_form).enableClientSideValidations();

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/projects/update.js.erb
$('#edit_project_<%= @project.id %>').remove();
$('#project-<%= @project.id %>').replaceWith("<%= j render @project %>");

app/views/tasks/_form.html.erb
<%= simple_form_for @task, remote: true do |f| %>
	<div class='task-input-group'>
	  <%= f.input :title, label: false %>
		  <div class="input-task-btn">
			  <%= f.button :submit, label: false, class: 'btn btn-primary' %>
		  </div>
	</div>
	<div class='task-input-group'>
		<%= f.input :deadline, html5: true, label: false%>
		<div class="input-task-status">
			  <%= f.input :status, label: false%>
		</div>
	</div>
	<div class='task-input-group'>
	  <%= f.input :project_id, label: false, :as => :hidden %>
	  <%= f.select :priority, Task::PRIORITIES, label: false %>
	</div>
<% end %>

app/views/tasks/_task.html.erb
<li class="task-item">
  <div id="task-<%= task.id %>" class="task task-header spriority_<%= task.priority %> completed_<%= task.status %>">
      <span><%= link_to content_tag('span', '', class: 'fa fa-check-square-o'), complete_task_path(task), data: {method: :put}, remote: true, class: 'done' %></span>
      <span class="task-item-title"><%= task.title %></span>
	<div class="task-header-options">
      <span class="task-item-edit"><%= link_to content_tag('span', '', class: 'fa fa-pencil'), edit_task_path(task), remote: true, class: 'action' %></span>
      <span class="task-item-destroy"><%= link_to content_tag('span', '', class: 'fa fa-trash'), task, method: :delete, remote: true, class: 'action' %></span>
	</div>
  </div>
</li>

app/views/tasks/complete.html.erb
<h1>Tasks#complete</h1>
<p>Find me in app/views/tasks/complete.html.erb</p>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/create.js.erb
$('#new-task form').remove();
$('#new-task a').show();
$('ul#tasks').prepend("<%= j render @task %>");

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<div class="col-md-12">
  <h1>Edit Task</h1>
</div>
<%= render 'form' %>

app/views/tasks/edit.js.erb
$('#task-<%= @task.id %>').hide().parent().prepend("<%= j render 'form', task: @task %>");

$(document).mouseup(function(e)
{
    let container = $('#edit_task_<%= @task.id %>');
    if (!container.is(e.target) && container.has(e.target).length === 0)
    {
        container.remove();
        $('#task-<%= @task.id %>').show();
    }

});

app/views/tasks/index.html.erb
<div class="col-md-12">
  <h1>SIMPLE TODO LIST</h1>

  <div class="buffer-top">
    <ul id="tasks">
      <% @tasks.each do |task| %>
        <%= render partial: 'task', object: task %>
      <% end %>

    <hr />

      <% @completed_tasks.each do |task| %>
        <%= render partial: 'task', object: task %>
      <% end %>
    </ul>
  </div>

  <hr />

  <div id="new-task">
    <%= link_to "New task", new_task_path, remote: true, class: 'btn btn-primary' %>
  </div>

  <hr />

</div>

app/views/tasks/new.html.erb
<div class="col-md-12">
  <h1>New Task</h1>
</div>
<%= render 'form' %>

app/views/tasks/new.js.erb
$('#new-task a').hide().parent().append("<%= j render 'form' %>");
$(document).mouseup(function(e)
{
    let container = $("#new-task form");
    if (!container.is(e.target) && container.has(e.target).length === 0)
    {
        container.remove();
        $('#new-task a').show();
    }
});

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>

app/views/tasks/update.js.erb
$('#edit_task_<%= @task.id %>').remove();
$('#task-<%= @task.id %>').replaceWith("<%= j render @task %>");